name: Release NPM (latest)

on:
  push:
    branches:
      - 'release/*'

jobs:
  publish-npm:
    name: Publish NPM module
    runs-on: ubuntu-latest
    environment: Release
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: npm install
      - run: npm run build:release
      - uses: cucumber/action-publish-npm@v1.1.1
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}
          npm-tag: 'latest'
